baseURL = "https://furkankambay.com"
languageCode = "en-us"
theme = "awesome-identity"
disableKinds = ["taxonomy", "term"]
title = "Furkan Kambay - Software Engineer"

[params.opengraph]
  description = "Software engineer, beginner in game development and penetration testing"
  images = ["/images/whoami.png"]

[params.profile]
  portrait = "/images/whoami.png"
  firstname = "Furkan"
  lastname = "Kambay"
  title = "Software Engineer, Game Developer"
  bio = """
  Hi, I'm Furkan. I'm a software engineer and game developer mostly experienced in C#, C++, Python, JavaScript.
  I love working on projects that I'm passionate about and learning new things along the way.
  
  I have experience in desktop/mobile apps, games in Unity, and some web development.
  
  I am also a beginner in penetration testing, reverse engineering, and electronics.
  """

[params.contacts]
  github = "FurkanKambay"
  linkedin = "FurkanKambay"
  stackoverflow = "4187549"
  hackthebox = "122166"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/FurkanKambay/furkankambay.github.io"

[params.footer]
  poweredBy = true
